name: Publish NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: init
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@gmail.com"
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
          cache: npm
          cache-dependency-path: '**/package.json'
      - run: |
          npm install
      - id: publish-camera
        name: publish camera
        uses: JS-DevTools/npm-publish@v4
        with:
          package: ./camera/package.json
          provenance: true
          access: public
          ignore-scripts: false
      - if: steps.publish-camera.outputs.old-version != steps.publish-camera.outputs.version
        name: tag camera
        run: |
          git tag "camera@${{ steps.publish-camera.outputs.version }}"
          git push origin "camera@${{ steps.publish-camera.outputs.version }}"
      - id: publish-preferences
        name: publish preferences
        uses: JS-DevTools/npm-publish@v4
        with:
          package: ./preferences/package.json
          provenance: true
          access: public
          ignore-scripts: false
      - if: steps.publish-preferences.outputs.old-version != steps.publish-preferences.outputs.version
        name: tag preferences
        run: |
          git tag "preferences@${{ steps.publish-preferences.outputs.version }}"
          git push origin "preferences@${{ steps.publish-preferences.outputs.version }}"
      - id: publish-app
        name: publish app
        uses: JS-DevTools/npm-publish@v4
        with:
          package: ./app/package.json
          provenance: true
          access: public
          ignore-scripts: false
      - if: steps.publish-app.outputs.old-version != steps.publish-app.outputs.version
        name: tag app
        run: |
          git tag "app@${{ steps.publish-app.outputs.version }}"
          git push origin "app@${{ steps.publish-app.outputs.version }}"
